#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TeamManager3.Resource", IsApplication=true)]

namespace TeamManager3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_person_add_black_18dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_person_add_white_18dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int splash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int united = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int DataHeader = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int DataRow = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int RosterListview = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int buttonDelete = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int buttonDone = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int buttonEdit = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int menuAddPlayer = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int playerName = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int playerNumber = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int toolbar = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DataListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditPlayer = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListGroup = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int Bottom_Menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int delete = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int done = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int edit = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int name = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int on_bench = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int on_pitch = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int roster = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int MyTheme_Splash = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
